# Generated by Django 5.2.5 on 2026-03-04 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_portfolio_video_url_portfolio_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='تم قراءتها')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='مؤسسة نجمة الإبداع', max_length=200, verbose_name='عنوان الموقع')),
                ('site_description', models.TextField(default='لتركيب وتوريد جميع أنواع زجاج السكريت', verbose_name='وصف الموقع')),
                ('phone', models.CharField(default='0534578698', max_length=20, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(default='966534578698', max_length=20, verbose_name='رقم الواتساب')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(default='خميس مشيط - حي الحسام', max_length=300, verbose_name='العنوان')),
                ('facebook', models.URLField(blank=True, verbose_name='رابط فيسبوك')),
                ('instagram', models.URLField(blank=True, verbose_name='رابط إنستجرام')),
                ('twitter', models.URLField(blank=True, verbose_name='رابط تويتر')),
                ('linkedin', models.URLField(blank=True, verbose_name='رابط لينكد إن')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('client_company', models.CharField(blank=True, max_length=100, verbose_name='اسم الشركة')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='التقييم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-order', '-date_added'], 'verbose_name': 'نموذج عمل', 'verbose_name_plural': 'نماذج الأعمال'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'خدمة', 'verbose_name_plural': 'الخدمات'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='فئة العمل'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف العمل'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتيب العمل'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان العمل'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='fas fa-check', max_length=50, verbose_name='أيقونة الخدمة'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتيب الخدمة'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
