# Generated by Django 5.2.5 on 2026-03-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactmessage_sitesettings_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_iframe_url',
            field=models.TextField(blank=True, help_text='انسخ رابط src من كود التضمين في خرائط جوجل', verbose_name='رابط تضمين الخريطة (Iframe URL)'),
        ),
    ]
